name: File Deleter
on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'File name to delete (e.g., sample.html)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  delete-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and delete specified files
        run: |
          # Store the input filename
          FILE_TO_DELETE="${{ github.event.inputs.filename }}"
          
          # Find all matching files and store their paths
          FOUND_FILES=$(find . -name "$FILE_TO_DELETE")
          
          # Check if any files were found
          if [ -z "$FOUND_FILES" ]; then
            echo "No files matching '$FILE_TO_DELETE' were found."
            exit 0
          fi
          
          # Print found files and delete them
          echo "Found the following matching files:"
          echo "$FOUND_FILES"
          echo "Deleting files..."
          
          find . -name "$FILE_TO_DELETE" -exec rm -f {} \;
          
          echo "Deletion complete."

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Delete all instances of ${{ github.event.inputs.filename }}" || echo "No changes to commit"

      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin HEAD:${GITHUB_REF#refs/heads/}
